import { useState } from 'react'
import ActivityDetailsModal from './ActivityDetailsModal'
import { formatEstimatedCost } from '../utils/formatters'

const categoryColors = ['bg-[#f4d9cf] text-[#9a4c3e]', 'bg-[#dbe9e4] text-[#49635d]', 'bg-[#eae3f2] text-[#6f5b8d]', 'bg-[#f0e7be] text-[#73611e]']
function categoryStyle(category) { return categoryColors[(category || '').split('').reduce((sum, char) => sum + char.charCodeAt(0), 0) % categoryColors.length] }

export default function ActivityCard({ activity, index, showSchedule = true, draggable = false, dragState, onDragStart, onDragEnd, onDragEnter, onDrop, onEdit, onDelete, onSelect, selected }) {
  const [detailsOpen, setDetailsOpen] = useState(false)
  const categories = activity.categories?.length ? activity.categories : activity.category ? [activity.category] : []
  const displayCost = formatEstimatedCost(activity.estimated_cost)

  return <><article draggable={draggable} onDragStart={onDragStart} onDragEnd={onDragEnd} onDragOver={(event) => event.preventDefault()} onDragEnter={onDragEnter} onDrop={onDrop} onClick={onSelect} className={`group overflow-hidden rounded-2xl border bg-white p-4 transition sm:p-5 ${dragState ? 'border-[#e0604e] ring-2 ring-[#f4d9cf]' : selected ? 'border-[#6f867e] ring-2 ring-[#dbe9e4]' : 'border-[#e6e2da] hover:border-[#b5beb8]'} ${draggable ? 'cursor-grab active:cursor-grabbing' : ''}`}>
    <div className={`flex min-w-0 flex-col gap-3 ${showSchedule ? 'sm:flex-row' : ''}`}>{showSchedule && <div className="flex shrink-0 items-center gap-3 sm:w-16 sm:flex-col sm:items-center sm:gap-0 sm:pt-0.5"><span className="font-serif text-xl text-[#263230]">{String(index + 1).padStart(2, '0')}</span><span className="text-center text-[10px] font-bold tracking-wide text-[#a1aaa5] sm:mt-1">STOP {index + 1}</span></div>}<div className="min-w-0 flex-1"><div className="flex min-w-0 flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex min-w-0 flex-wrap items-center gap-2"><h3 className="min-w-0 break-words font-semibold text-[#263230]">{activity.name}</h3>{categories.map((category) => <span key={category} className={`max-w-full break-words rounded-full px-2.5 py-1 text-center text-[10px] font-bold tracking-wide ${categoryStyle(category)}`}>{category}</span>)}{activity.source_url && <span className="shrink-0 text-xs" title="Saved from TikTok">◉</span>}</div><p className="mt-1 break-words text-sm text-[#7d8782]">{activity.address || 'Location pending'}</p>{activity.submitted_by && <p className="mt-2 break-words text-xs font-medium text-[#89938e]">Added by {activity.submitted_by}</p>}</div><div className="flex max-w-full flex-wrap items-center gap-1.5 lg:shrink-0 lg:justify-end">{displayCost && <span className="max-w-full break-words px-1 text-sm font-semibold text-[#52635e]">{displayCost}</span>}<button type="button" onClick={(event) => { event.stopPropagation(); setDetailsOpen(true) }} className="whitespace-nowrap rounded-lg px-2 py-1 text-sm text-[#68716d] hover:bg-[#f6f3ed]">Details</button><button type="button" onClick={(event) => { event.stopPropagation(); onEdit(activity) }} className="whitespace-nowrap rounded-lg px-2 py-1 text-sm text-[#68716d] hover:bg-[#f6f3ed]">Edit</button><button type="button" onClick={(event) => { event.stopPropagation(); onDelete(activity) }} className="shrink-0 rounded-lg px-2 py-1 text-sm text-[#b45645] hover:bg-[#fff1ed]" aria-label={`Delete ${activity.name}`}>×</button></div></div></div></div>
  </article>{detailsOpen && <ActivityDetailsModal activity={activity} onClose={() => setDetailsOpen(false)} onEdit={onEdit} />}</>
}
