import { formatOperatingHours } from '../utils/formatters'

export default function TikTokInbox({ tiktok, setTikTokLink, onMetadata, onTranscript, onApprove, onReject }) {
  const { link, metadata, transcript, extraction, metadataLoading, transcriptLoading, extractionLoading, savingCandidate } = tiktok
  return <section className="mx-auto max-w-4xl px-5 py-7 sm:px-8 sm:py-10"><p className="text-xs font-bold tracking-[.18em] text-[#e0604e]">TIKTOK INBOX</p><h2 className="mt-2 font-serif text-4xl tracking-[-.04em] text-[#263230]">Turn saved videos into real plans.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#7d8782]">Paste a video and we’ll extract potential places from its preview. Nothing is added without your approval.</p><div className="mt-8 rounded-3xl border border-[#dedbd3] bg-white p-5 sm:p-7"><div className="flex flex-wrap items-center gap-2 text-xs font-bold tracking-[.12em] text-[#71817b]"><span className="rounded-full bg-[#263230] px-2.5 py-1 text-white">1 LINK</span><span>—</span><span>2 EXTRACT</span><span>—</span><span>3 REVIEW</span></div><form className="mt-6 flex flex-col gap-3 sm:flex-row" onSubmit={(event) => { event.preventDefault(); onMetadata() }}><input className="min-w-0 flex-1 rounded-xl border border-[#dedbd3] px-4 py-3 outline-none focus:border-[#6f867e]" type="url" value={link} onChange={(event) => setTikTokLink(event.target.value)} placeholder="Paste a TikTok link" required /><button className="rounded-xl bg-[#263230] px-5 py-3 font-bold text-white disabled:opacity-60" disabled={metadataLoading || extractionLoading}>{metadataLoading || extractionLoading ? 'Extracting…' : 'Extract places'}</button></form>
      {metadata && <div className={`mt-6 rounded-2xl border p-5 ${metadata.detected ? 'border-[#b7d2c7] bg-[#edf5f0]' : 'border-[#edcf89] bg-[#fff8e7]'}`}><p className="font-semibold text-[#263230]">{metadata.detected ? 'Video details found' : 'We could not read that video'}</p><p className="mt-1 text-sm leading-6 text-[#5f6d68]">{metadata.message}</p>{metadata.detected && <><p className="mt-4 rounded-xl bg-white/70 p-4 text-sm leading-6 text-[#53615c]">{metadata.caption}</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={onTranscript} disabled={transcriptLoading || extractionLoading} className="rounded-lg border border-[#78968c] px-3 py-2 text-sm font-semibold text-[#49635d] disabled:opacity-60">{transcriptLoading || extractionLoading ? 'Refining…' : 'Get transcript & refine'}</button></div></>}</div>}
      {transcript && <div className="mt-4 rounded-2xl bg-[#f6f3ed] p-5"><p className="font-semibold">{transcript.detected ? 'Transcript' : 'Transcript unavailable'}</p><p className="mt-2 text-sm text-[#68716d]">{transcript.message}</p>{transcript.detected && <p className="mt-3 max-h-40 overflow-y-auto whitespace-pre-wrap text-sm leading-6 text-[#53615c]">{transcript.text}</p>}</div>}
    </div>
    {extraction && <div className="mt-7"><div className="flex items-center justify-between"><div><p className="text-xs font-bold tracking-[.18em] text-[#6f5b8d]">READY FOR REVIEW</p><h3 className="mt-1 font-serif text-2xl">Potential places</h3></div><span className="rounded-full bg-[#eae3f2] px-3 py-1 text-sm text-[#6f5b8d]">{extraction.activities?.length || 0}</span></div><p className="mt-2 text-sm text-[#7d8782]">{extraction.message}</p><div className="mt-5 grid gap-4">{extraction.activities?.map((candidate) => <article className="rounded-2xl border border-[#ded7e5] bg-white p-5" key={`${candidate.activity_name}-${candidate.poi_name}`}><div className="flex flex-wrap justify-between gap-3"><div><h4 className="font-semibold text-[#263230]">{candidate.activity_name}</h4><p className="mt-1 text-sm text-[#68716d]">{candidate.poi_name}</p><div className="mt-2 flex flex-wrap gap-1.5">{candidate.categories.map((category) => <span key={category} className="rounded-full bg-[#eae3f2] px-2 py-1 text-[10px] font-bold tracking-wide text-[#6f5b8d]">{category}</span>)}</div></div>{candidate.estimated_cost && <span className="font-semibold text-[#52635e]">{candidate.estimated_cost}</span>}</div><div className="mt-4 grid gap-2 text-sm text-[#68716d] sm:grid-cols-2"><p>{candidate.poi_address || 'Address not resolved'}</p><p>{formatOperatingHours(candidate.operating_hours)}</p></div><p className={`mt-3 text-sm ${candidate.geocoded ? 'text-[#417363]' : 'text-[#a87928]'}`}>{candidate.geocoded ? 'Location and visiting hours confirmed' : candidate.geocoding_message || 'Location needs confirming'}</p><div className="mt-5 flex gap-2"><button type="button" onClick={() => onApprove(candidate)} disabled={savingCandidate === candidate.activity_name} className="rounded-lg bg-[#263230] px-3 py-2 text-sm font-bold text-white disabled:opacity-60">{savingCandidate === candidate.activity_name ? 'Saving…' : 'Keep place'}</button><button type="button" onClick={() => onReject(candidate)} className="rounded-lg px-3 py-2 text-sm font-semibold text-[#a54f40] hover:bg-[#fff1ed]">Discard</button></div></article>)}{extraction.activities?.length === 0 && <div className="rounded-2xl border border-dashed border-[#c7ceca] p-7 text-sm text-[#7d8782]">No new places are waiting for review.</div>}</div></div>}
  </section>
}
