import { useState } from 'react'

export default function TripEditModal({ trip, onClose, onSave, submitting }) {
  const [form, setForm] = useState(() => ({ name: trip.name, destination_city: trip.destination_city || '', destination_region: trip.destination_region || '', start_date: trip.start_date, end_date: trip.end_date }))
  const update = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }))
  const submit = async (event) => { event.preventDefault(); const saved = await onSave(form); if (saved) onClose() }

  return <div className="fixed inset-0 z-50 grid place-items-center bg-[#263230]/45 p-5" role="dialog" aria-modal="true" aria-label="Edit trip information"><form onSubmit={submit} className="w-full max-w-xl rounded-[1.8rem] bg-[#fdfbf7] p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold tracking-[.18em] text-[#e0604e]">TRIP SETTINGS</p><h2 className="mt-2 font-serif text-3xl tracking-[-.04em] text-[#263230]">Refine the plan.</h2></div><button type="button" onClick={onClose} className="rounded-lg px-2 py-1 text-xl text-[#68716d] hover:bg-[#f0eee8]" aria-label="Close trip settings">×</button></div><p className="mt-3 text-sm leading-6 text-[#68716d]">Travel dates can be changed as long as every scheduled activity still falls within the new range.</p><div className="mt-7 grid gap-4"><label>Trip name<input required name="name" value={form.name} onChange={update} maxLength="160" /></label><div className="grid gap-4 sm:grid-cols-2"><label>Destination city<input name="destination_city" value={form.destination_city} onChange={update} maxLength="120" placeholder="Kyoto" /></label><label>Destination region<input name="destination_region" value={form.destination_region} onChange={update} maxLength="120" placeholder="Kansai" /></label></div><div className="grid gap-4 sm:grid-cols-2"><label>Start date<input required type="date" name="start_date" value={form.start_date} onChange={update} /></label><label>End date<input required type="date" name="end_date" min={form.start_date} value={form.end_date} onChange={update} /></label></div></div><button disabled={submitting} className="mt-7 w-full rounded-xl bg-[#263230] px-5 py-3.5 font-bold text-white hover:bg-[#374744] disabled:opacity-60">{submitting ? 'Saving…' : 'Save trip changes'}</button></form></div>
}
