import { formatDate } from '../utils/formatters'

export default function TripHeader({ trip, members = [], trips, selectedTripId, onSelectTrip, onNewActivity, onShare, onEditTrip, onGoHome, onExport }) {
  const destination = [trip.destination_city, trip.destination_region].filter(Boolean).join(', ') || 'Your next destination'
  return <header className="border-b border-[#dedbd3] bg-[#fdfbf7] px-5 py-5 sm:px-8">
    <div className="mx-auto flex max-w-[1600px] flex-wrap items-center justify-between gap-4">
      <div className="flex min-w-0 items-center gap-3 sm:gap-5"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-[#263230] font-serif text-xl text-[#f6b5a7]">J</div><div className="min-w-0"><p className="text-[10px] font-bold tracking-[.22em] text-[#e0604e]">JETSETGO / TRIP PLANNER</p><h1 className="truncate font-serif text-2xl tracking-[-.03em] sm:text-3xl">{trip.name}</h1></div></div>
      <div className="flex items-center gap-2 sm:gap-3"><button type="button" className="rounded-lg px-3 py-2 text-sm font-semibold text-[#68716d] hover:bg-[#f6f3ed]" onClick={onGoHome}>All trips</button><select aria-label="Change active trip" className="hidden max-w-44 rounded-lg border border-[#dedbd3] bg-white px-3 py-2 text-sm sm:block" value={selectedTripId || ''} onChange={(event) => onSelectTrip(Number(event.target.value))}>{trips.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><button type="button" className="rounded-lg border border-[#dedbd3] bg-white px-3 py-2 text-sm font-semibold hover:bg-[#f6f3ed]" onClick={onEditTrip}>Edit trip</button><button type="button" className="hidden rounded-lg border border-[#dedbd3] bg-white px-3 py-2 text-sm font-semibold hover:bg-[#f6f3ed] sm:block" onClick={onExport}>Export PDF</button><button type="button" className="rounded-lg border border-[#dedbd3] bg-white px-3 py-2 text-sm font-semibold hover:bg-[#f6f3ed]" onClick={onShare}>Share</button><button type="button" className="rounded-lg bg-[#263230] px-3 py-2 text-sm font-bold text-white hover:bg-[#374744] sm:px-4" onClick={onNewActivity}>+ Add place</button></div>
    </div>
    <div className="mx-auto mt-4 flex max-w-[1600px] flex-wrap items-center gap-x-4 gap-y-2 text-sm text-[#68716d]"><span>{destination}</span><span className="hidden h-1 w-1 rounded-full bg-[#a5aba8] sm:block" /><span>{formatDate(trip.start_date, { month: 'short', day: 'numeric' })} – {formatDate(trip.end_date, { month: 'short', day: 'numeric', year: 'numeric' })}</span>{members.length > 0 && <div className="flex flex-wrap items-center gap-1.5" aria-label="Trip members">{members.slice(0, 4).map((member) => <span key={member.id} title={member.username ? `${member.name} (@${member.username})` : member.name} className="rounded-full bg-[#e7eee9] px-2.5 py-1 text-xs font-semibold text-[#49635d]">{member.name}</span>)}{members.length > 4 && <span className="rounded-full bg-[#e7eee9] px-2.5 py-1 text-xs font-semibold text-[#49635d]">+{members.length - 4}</span>}</div>}<span className="ml-auto flex items-center gap-1 text-xs"><span className="grid h-6 w-6 place-items-center rounded-full border-2 border-[#fdfbf7] bg-[#e0b3a6] font-bold text-[#263230]">↗</span> Share code ready</span></div>
  </header>
}
